---
title: "p2_assays"
author: "Shoshana Rapley"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

This Markdown documents pre-release assays and post-release survival and establishment metrics for translocated
bush stone-curlews (curlews) at Mt Rothwell, Victoria. 

# Post-release data

Data are stored on Movebank, and were downloaded for the period 25/10/2022 to 10/05/2023. Data are cleaned to 
remove erroneous GPS fixes. 

```{r data clean}

birds <- c("Briar", "Nutmeg", "Star", "Aurora", "Robin", "Daisy",
           "Iona", "Sage", "Koda", "Brook", "Clover", "Wobbles",
           "Prem", "Rove", "Valentine", "Marmalade")

data_raw <- read.csv("movebank_20230510.csv") %>%
  clean_names() %>%
  rename(id = individual_local_identifier,
         lon = location_long,
         lat = location_lat,
         qi = gps_satellite_count) %>%
  filter(id %in% birds) %>%
  mutate(DateTime = as.POSIXct(study_local_timestamp,
                               "%Y-%m-%d %H:%M:%S",
                               tz = "Australia/Sydney")) %>%
  mutate(date = date(DateTime))

data_hdop <- data_raw %>%
  filter(qi>5,
         gps_hdop<1.4) #hdop recent addition 16 jan to improve accuracy

data_filt <- data_hdop %>%
  dupfilter() %>%
  ddfilter_speed(vmax=4, method=2)%>%
  rename(date_time = DateTime)

data <- data_filt

### plot data cleaning
map <- get_map(c(144.435738, -37.900544), zoom=14, maptype = "satellite")
ggmap(map)+
  geom_point(data=data_raw, aes(lon, lat), color="red")+
  geom_point(data=data_hdop, aes(lon, lat), color="yellow")+
  geom_point(data=data_filt, aes(lon, lat), color="blue")


```

